### ISSUE TITLE
Metadata migrations not published

### ISSUE THREAD

**Issue by martianatwork** [rennokki/plans#43]
You forgot to update service provider.

Also seems like you came from 2019 :P jk.

**Comment by rennokki** [comment]
Hey, thank you for noticing it. I wouldn't have been able to notice that. There's an incoming PR here: https://github.com/rennokki/plans/pull/44

It was more like a crazy idea at first to start writing this package, but it seems it worked at some level. Comparing to other subscriptions services, this is kinda' rudimentary, since there's not invoicing, but it's a good start if someone wants to build more on scaffolding.
