### ISSUE TITLE
Infinite Subscription?

### ISSUE THREAD

**Issue by martianatwork** [rennokki/plans#45]
So I'm in the scenario where we have a basic plan with infinite days.
I tried to use 
`>>> $user->subscribeTo($plan,-1,false)`
Which returns false

I could do something like this 
`>>> $user->subscribeTo($plan,999999999,false)`

But then again upgrading the plan will cause issues.

We can accept -1 which will give the plan infinite time.

**Comment by rennokki** [comment]
Hey @martianatwork,

Thank you for putting interest into it. I really appreciate when people come with new ideas that make the product better.

I will think to a solution for this. Basically, you can set up in an in-aesthetic way with a ton of 9's, but you can also set a future date, like this:

```php
$user->subscribeToUntil($plan, '2030-12-21');
```

When upgrading, you can do so with dates too. Basically, the subscription has an ending date. Usually, the upgrade should be done when the current subscription ends. However, if you want it to start now, you can pass `true` as the third parameter:
```php
$user->upgradeCurrentPlanToUntil($anotherPlan, '2030-12-21', true);
```

This will upgrade your subscription's plan right now, and explicitly update the date to that date passed as the second parameter.

Since this is not so aesthetic, this is the only work-around. But i'll send this to the Projects board to work on it. :D
