### ISSUE TITLE
How to get the plan data?

### ISSUE THREAD

**Issue by SaphiLC** [rennokki/plans#51]
Im making a view composer to show the plan name the current user has:
```
if (!Auth::check()) {
	return;
}

$view->with([
	'plan' => Auth::user()->activeSubscription(),
]);
```
but no idea how to get the name or any info from that plan, i can use {{ $plan->remainingDays() }} in blade and works, shows the correct remaining days, but no idea how to access the plan data. The documentation is not very good :( sorry

**Comment by rennokki** [comment]
Hey @SaphiLC, what do you refer by "plan data"? You want to retrieve actual plan data from the API?

**Comment by SaphiLC** [comment]
like, the name of the plan, i tried many things but no luck :(
in the example above, i tried $plan->name but nope, i would expect being able to access the name since im getting the active subscription :(

**Comment by rennokki** [comment]
Don't worry. Usually, a good practice makes to use methods in order to retrieve either a relationship or some data. In this case, might be used for a relationship, like `activeSubscription()`, but this will already retrieve your object.

Calling `activeSubscription()` retrieves you [https://github.com/rennokki/plans/blob/master/src/Models/PlanSubscriptionModel.php](this model)  and you have methods to retrieve the full plan:
```
$plan = $user->activeSubscription()->plan()->first();
```
